### ISSUE TITLE
[Discord/BetterDiscord] Themes doesn't work [Bug] 

### ISSUE THREAD

**Issue by FlyingCat-X** [owl4ce/dotfiles#107]
**Describe the bug**
When activating a theme in discord (I tried with both themes) there isn't change.

**Expected behavior**
Themes are activated correctly when they are selected.

**Screenshots**
- Here I disabled and re-enabled the theme so that I could take a screenshot of it.
![image](https://user-images.githubusercontent.com/33896771/119421750-0c8bcd80-bcc5-11eb-898c-e4309f23bde4.png)
![image](https://user-images.githubusercontent.com/33896771/119421888-58d70d80-bcc5-11eb-952f-a00c2ccd9178.png)

**Desktop (please complete the following information):**
 - **OS**: Arch Linux 5.12.6-zen1-1-zen
 - **Discord version**: 0.0.14-1
 - **BetterDiscord version**: [1.1.1](https://github.com/rauenzi/BetterDiscordApp)

**Additional context**
One of the css used in the imports has been deleted. `https://codedotspectra.github.io/themes/nocturnal/importCSS/core.css`
![image](https://user-images.githubusercontent.com/33896771/119422331-7a84c480-bcc6-11eb-8e47-e544622a5ecb.png)
Removed in [this commit](https://github.com/codedotspectra/themes/commit/c4cd7749379db09fee35481368d6b5fcdbf29249).

**Comment by owl4ce** [comment]
**Hi @FlyingCat-X**
I'm sorry. I'm not developing/provide betterdiscord themes because I don't run discord. 

@pr1nce55 can you help this?

**Comment by FlyingCat-X** [comment]
It's okay. Is there any other repo where I can submit the issue?

**Comment by FlyingCat-X** [comment]
I managed to fix it in case someone else has the same problem as me. I made a few changes to the css file

```css
@import "https://flashal.github.io/Nocturnal-discord-theme/nocturnal/importCSS/circle_core.css";
@import "https://monstrousdev.github.io/themes/addons/user-tags.css";
@import "https://codedotspectra.github.io/themes/core/badges.css";

:root {
    --primary: #CF8EF4;
    --primaryGradient2: #63C5EA;
    --backgroundDark: #373E4D;
    --backgroundDarker: rgba(20,23,31,0.95);
}

.theme-dark {
    --background-tertiary: rgba(55,62,77,0.95);
    --background-secondary: rgba(55,62,77,0.95);
}

.expandedFolderBackground-2sPsd-,.expandedFolderBackground-1cujaW {
    background-color: rgba(55,62,77,0.95)!important;
    border-radius: 12px;
}

.folder-21wGz3,.folder-1hbNCn {
    background-color: rgba(55,62,77,0.95)!important;
    border-radius: 12px;
}
```
![image](https://user-images.githubusercontent.com/33896771/119576044-a0b96b80-bd7d-11eb-9441-0f64bbe60fba.png)
